---
- name: Configure Server
  hosts: servers
  gather_facts: no  # 초기에는 facts 수집 비활성화
  become: yes  # sudo 권한 사용

  pre_tasks:
    - name: Bootstrap Python
      raw: apt-get update && apt-get install -y python3 python3-pip python3-six python3-apt

    - name: Install Python required packages
      raw: apt-get install -y python-is-python3 python3-setuptools

    - name: Setup facts
      setup:

    
  roles:
    - common
    #- ssh-keys
    #- docker
    #- app