# jenkins-user/meta/main.yml
---
galaxy_info:
  role_name: jenkins_user
  author: puzzle-ai infra
  description: Role to create and configure jenkins user for CI/CD deployment
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - jenkins
    - deployment
    - ci
    - cd